TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score'] 
    num_max_boxes: 50
    # image_shape: [3, None, None]
    # use_dataloader: True,
    # iterable: False
  #### 数据源配置
  dataset:  
    !InsectsDataSet
      anno_dir: train
      dataset_dir: dataset/insects
  #### transfrom ####
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeBox {}
  - !ExpandImage
    max_ratio: 4.0
    mean: [123.675, 116.28, 103.53]
    prob: 0.5
  - !RandomInterpImage
    max_size: 0
    target_size: 608
#   - !RandomFlipImage
#     is_normalized: true
#     prob: 0.5
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: true
    is_channel_first: false
  - !PadBox
    num_max_boxes: 50
  - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [608]
  - !Permute
    channel_first: true
    to_bgr: false
  #### data ####
  batch_size: 1
  shuffle: true
  drop_last: false
  drop_empty: true
  #### sampling ####  
  mixup_epoch: -1
  class_aware_sampling: false
  #### multi-process ####
  worker_num: -1
  # bufsize: 32
  # use_process: true


EvalReader:
  inputs_def:
    fields: ['image', 'im_size']
    # num_max_boxes: 50
#   dataset:
#     !COCODataSet
#       image_dir: val2017
#       anno_path: annotations/instances_val2017.json
#       dataset_dir: dataset/coco
#       with_background: false
#   sample_transforms:
#     - !DecodeImage
#       to_rgb: True
#     - !ResizeImage
#       target_size: 608
#       interp: 2
#     - !NormalizeImage
#       mean: [0.485, 0.456, 0.406]
#       std: [0.229, 0.224, 0.225]
#       is_scale: True
#       is_channel_first: false
#     - !PadBox
#       num_max_boxes: 50
#     - !Permute
#       to_bgr: false
#       channel_first: True
#   batch_size: 8
#   drop_empty: false
#   worker_num: 8
#   bufsize: 32

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
#     fields: ['image', 'im_size', 'im_id']
#   dataset:
#     !ImageFolder
#       anno_path: annotations/instances_val2017.json
#       with_background: false
#   sample_transforms:
#     - !DecodeImage
#       to_rgb: True
#     - !ResizeImage
#       target_size: 608
#       interp: 2
#     - !NormalizeImage
#       mean: [0.485, 0.456, 0.406]
#       std: [0.229, 0.224, 0.225]
#       is_scale: True
#       is_channel_first: false
#     - !Permute
#       to_bgr: false
#       channel_first: True
#   batch_size: 1
