architecture: YOLOv3
use_gpu: True
# use_gpu: false
max_iters: 200
log_iter: 20
log_smooth_window: 20
snapshot_iter: 2000
save_dir: output
metric: VOC
map_type: 11point
#### 迁移学习 ####
# pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/DarkNet53_pretrained.tar
pretrain_weights: 
# finetune_exclude_pretrained_params: 

# weights: output/yolov3_darknet/model_final

# 全局类实例化参数
num_classes: 7
use_fine_grained_loss: false



YOLOv3:
  backbone: DarkNet
  yolo_head: YOLOv3Head
########
# use_fine_grained_loss
# mixed_precision

DarkNet:
  norm_type: bn
  norm_decay: 0.
  depth: 53

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[19, 29], [28, 20], [25, 40], 
            [31, 47], [36, 37], [41, 26], 
            [47, 66], [48, 33], [67, 53]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  batch_size: 8
  ignore_thresh: 0.7
  label_smooth: false

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 400000
    - 450000
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_darknet_insects_reader.yml'

